[package]
name = "termhub-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "termhub"
path = "src/main.rs"

[dependencies]
termhub-core    = { workspace = true }
termhub-drivers = { workspace = true }
termhub-sshd    = { workspace = true }
tokio           = { workspace = true }
anyhow          = { workspace = true }
tracing         = { workspace = true }
tracing-subscriber = { workspace = true }
